namespace Ali.Infrastructure.Voice;

public sealed record VoiceRuntimeSettings(
    int? SelectedInputDeviceNumber = null,
    string? SelectedInputDeviceName = null,
    int? SelectedOutputDeviceNumber = null,
    string? SelectedOutputDeviceName = null,
    int? LastSuccessfulSttDeviceNumber = null,
    string? LastSuccessfulSttDeviceName = null,
    int? LastSuccessfulTtsDeviceNumber = null,
    string? LastSuccessfulTtsDeviceName = null,
    string SelectedInputPreset = VoiceInputPreset.HeadsetMic,
    string SelectedInputChannelMode = nameof(InputChannelMode.MonoSum),
    double ExtraInputGainDb = 6,
    bool NormalizeBeforeStt = true,
    bool RetainDebugAudio = false,
    bool AssistantReadsRepliesOutLoud = false,
    bool AutoSendVoiceTranscripts = false,
    string PushToTalkKey = "NumPad0",
    string? WhisperExecutablePath = null,
    string? WhisperModelPath = null,
    string? WhisperArgumentsTemplate = null,
    string? PiperExecutablePath = null,
    string? PiperModelPath = null,
    string? PiperVoiceId = null,
    string? PiperArgumentsTemplate = null);
