<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ali.App.VisualStudioExtension</RootNamespace>
    <AssemblyName>Ali.App.VisualStudioExtension</AssemblyName>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Ali.Modules\Programming Depricated\**\*.cs" />
    <None Include="Ali.Modules\Programming Depricated\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="AliCompanionPackage.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\AliCompanionIcon.png">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\AliCompanionCommandIcon.png">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" />
  </ItemGroup>

</Project>
